In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

In [48]:
df = pd.read_csv("Data_Marketing_Customer_Analysis_Round3.csv")
cats=df.select_dtypes(include="object")
nums=df.select_dtypes(include="number")

In [49]:
X=nums.drop('total_claim_amount', axis=1)
y=pd.DataFrame(nums["total_claim_amount"])

In [50]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=.30,random_state=123)

In [51]:
std_scaler=StandardScaler().fit(X_train)

In [52]:
X_train_scaled=std_scaler.transform(X_train)
X_test_scaled=std_scaler.transform(X_test)

In [53]:
print(X_train_scaled)
print("___________________________________________________________________ \n")
print(X_test_scaled)

[[-0.11021627 -1.27291744 -0.67143823 ...  1.36516733 -0.42500069
  -0.40381143]
 [-0.42794064  0.74729478 -0.72925469 ...  1.68786198 -0.42500069
   0.84759702]
 [-0.5223013   0.26592193  0.48489091 ...  0.50464827 -0.42500069
  -0.82094758]
 ...
 [-0.81132612 -1.17224873 -0.90270406 ... -1.39566466 -0.42500069
  -0.82094758]
 [ 2.25575772  0.98537142 -0.78707115 ... -1.61079442 -0.42500069
  -0.40381143]
 [ 1.18923585  0.68583346 -0.55580532 ...  0.21780858  1.78399907
  -0.40381143]]
___________________________________________________________________ 

[[-0.40967729  1.58428551 -0.61362178 ...  1.54444214 -0.42500069
   2.51614162]
 [-0.7597249  -0.93947257 -0.64253    ...  0.755633    0.67949919
  -0.82094758]
 [ 0.57248529 -1.23371005 -0.90270406 ...  0.39708339 -0.42500069
  -0.40381143]
 ...
 [-0.79857077 -1.05867274 -0.58471355 ... -1.18053489 -0.42500069
  -0.82094758]
 [-0.42547654 -0.97370317 -0.81597938 ... -1.61079442  0.67949919
   0.43046087]
 [-0.49881985 -0.95695203  0

In [54]:
X_train_const_scaled = sm.add_constant(X_train_scaled) # adding a constant

model = sm.OLS(y_train, X_train_const_scaled).fit()
predictions_train = model.predict(X_train_const_scaled) 

X_test_const_scaled = sm.add_constant(X_test_scaled) # adding a constant
predictions_test = model.predict(X_test_const_scaled) 
print_model = model.summary()
print(print_model)

                            OLS Regression Results                            
Dep. Variable:     total_claim_amount   R-squared:                       0.410
Model:                            OLS   Adj. R-squared:                  0.410
Method:                 Least Squares   F-statistic:                     742.9
Date:                Wed, 09 Nov 2022   Prob (F-statistic):               0.00
Time:                        16:05:05   Log-Likelihood:                -51168.
No. Observations:                7482   AIC:                         1.024e+05
Df Residuals:                    7474   BIC:                         1.024e+05
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        433.0597      2.612    165.770      0.0

In [56]:
predictions_test

array([260.52304948, 353.76752657, 297.68091412, ..., 367.57334203,
       317.67903438, 608.06079373])

In [60]:
model=LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

In [64]:
X_train

customer_lifetime_value  income  monthly_premium_auto  \
6608                      7271   20545                    70   
5697                      5079   70474                    68   
10524                     4428   58577                   110   
397                      22332   49078                    97   
6324                      2430   26182                    70   
...                        ...     ...                   ...   
9785                      3086   73938                    76   
7763                      5658   78834                    72   
5218                      2434   23033                    62   
1346                     23594   76358                    66   
3582                     16236   68955                    74   

       months_since_last_claim  months_since_policy_inception  \
6608                        23                             86   
5697                         6                             95   
10524                        6                             62   
397                         10                              3   
6324                        29                             30   
...                        ...                            ...   
9785                        34                             48   
7763                        14                             20   
5218                         5                              9   
1346                        25                              3   
3582                        24                             54   

       number_of_open_complaints  number_of_policies  
6608                           0                   2  
5697                           0                   5  
10524                          0                   1  
397                            0                   2  
6324                           0                   1  
...                          ...                 ...  
9785                           0                   1  
7763                           2                   8  
5218                           0                   1  
1346                           0                   2  
3582                           2                   2  

[7482 rows x 7 columns]

In [70]:
new_data=[5000,50000,100,6,37,1,3]
new_data_scaled=std_scaler.transform(np.array(new_data).reshape(-1,7))

/Users/Clement/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [65]:
model.coef_

array([[ -6.5986299 , -33.18126217, 187.80190938,   1.90598135,
         -0.91148552,   1.71705592,  -2.32015745]])

In [66]:
model.intercept_

array([433.05974338])

In [75]:
y_pred=model.predict(X_test_scaled)   # model prediction

y_pred_train=model.predict(X_train_scaled)

y_pred

array([[260.52304948],
       [353.76752657],
       [297.68091412],
       ...,
       [367.57334203],
       [317.67903438],
       [608.06079373]])

In [68]:
y_test

total_claim_amount
4665                  345
4072                  345
4549                  257
4211                  445
3081                  523
...                   ...
3488                  404
1667                  554
1516                  350
10215                  27
2931                  320

[3207 rows x 1 columns]

In [85]:
y_test_np=np.array(y_test).reshape(-1,3207)
y_test_np

array([[345, 345, 257, ..., 350,  27, 320]])

In [71]:
model.predict(new_data_scaled)

array([[475.19595967]])

In [86]:
result=pd.DataFrame({"y_test":y_test_np,"y_pred":y_pred})

ValueError: Per-column arrays must each be 1-dimensional